#!/usr/bin/env python3
"""
Parser de G-code : extrait le filament utilisé (mm/m et g) depuis les fichiers
produits par Creality Print (basé sur Klipper/Marlin), OrcaSlicer, PrusaSlicer, Cura.
"""
import re


# Formats de commentaires rencontrés dans les slicers
# - Creality/Klipper  : ; filament used [mm] = 1234.56  (ou [g])
# - PrusaSlicer       : ; Filament used: 2.34m / 1.23g  (ou ; filament used [mm] = ...)
# - Cura              : ;Filament used: 2.34m
# - Klipper (raw)     : ; total filament used [g] = 3.2
# - Extrusion brute   : compter les lignes G1 E<value> et sommer les deltas

def parse_filament(text: str) -> dict:
    """Renvoie {'mm': float|None, 'g': float|None, 'raw_mm': float|None}"""
    out = {"mm": None, "g": None, "raw_mm": None}

    # 1) Forme '; filament used [g] = 4.32' (Klipper moderne)
    m = re.search(r";\s*(?:total\s+)?filament\s+used\s*\[\s*g\s*\]\s*=\s*([0-9.]+)", text, re.I)
    if m:
        out["g"] = float(m.group(1))

    # 2) Forme '; filament used [mm] = 1234.56'
    m = re.search(r";\s*filament\s+used\s*\[\s*mm\s*\]\s*=\s*([0-9.]+)", text, re.I)
    if m:
        out["mm"] = float(m.group(1))

    # 3) Forme '; Filament used: 2.34m' ou ';Filament used: 2.34m / 3.2g'
    m = re.search(r";\s*filament\s+used\s*:\s*([0-9.]+)\s*m", text, re.I)
    if m:
        out["mm"] = float(m.group(1)) * 1000.0  # conversion m → mm

    m = re.search(r";\s*filament\s+used\s*:\s*([0-9.]+)\s*m\s*/\s*([0-9.]+)\s*g", text, re.I)
    if m:
        out["mm"] = float(m.group(1)) * 1000.0
        out["g"] = float(m.group(2))

    # 4) Méta ';FILAMENT_USED[mm]=' (certains nombreux)
    m = re.search(r";\s*FILAMENT_USED\s*\[\s*mm\s*\]\s*=\s*([0-9.]+)", text, re.I)
    if m and out["mm"] is None:
        out["mm"] = float(m.group(1))

    # 5) Estimation brute par sommation des E (si rien trouvé au-dessus)
    if out["mm"] is None:
        total = 0.0
        last = None
        for line in text.splitlines():
            m = re.search(r"\bG1\b.*\bE(-?[0-9.]+)", line, re.I)
            if m:
                e = float(m.group(1))
                if last is not None:
                    total += max(0.0, e - last)
                last = e
        if total > 0:
            out["raw_mm"] = round(total, 2)
            out["mm"] = out["raw_mm"]

    # g depuis mm via densité par défaut (1.75mm PLA ≈ 2.63 g/m si densité 1.24)
    # on ne le force pas ici — l'app connaît la densité du filament choisi
    return out


# Densité par défaut pour conversion mm → g (PLA 1.24 g/cm³, Ø1.75)
FILAMENT_DENSITY = {"PLA": 1.24, "PETG": 1.27, "ABS": 1.04, "ASA": 1.07,
                    "TPU": 1.21, "PC": 1.20, "Nylon": 1.08, "PA": 1.08}


def mm_to_grams(mm: float, diameter_mm: float = 1.75, density: float = 1.24) -> float:
    """Convertit une longueur de filament (mm) en grammes."""
    radius = diameter_mm / 2
    volume_mm3 = 3.14159265 * radius * radius * mm       # mm³
    return round(volume_mm3 * density / 1000.0, 2)        # g


# ---------- Miniatures (thumbnails) encodées dans les G-code ----------
# Formats observés :
#   ; thumbnail begin 400x300     ...base64...    ; thumbnail end          (PrusaSlicer)
#   ; thumbnail_JPG begin 400x300 ...base64...    ; thumbnail_JPG end      (OrcaSlicer / Creality)
#   ; thumbnail_PNG begin ...                    ; thumbnail_PNG end
import base64 as _b64

_THUMB_START = re.compile(r";\s*thumbnail(?:_(JPG|PNG))?\s+begin\s*\d+x\d+", re.I)
_THUMB_END = re.compile(r";\s*thumbnail(?:_(JPG|PNG))?\s+end", re.I)


def extract_thumbnail(text: str) -> dict | None:
    """Extrait la miniature encodée en base64 depuis le G-code.
    Renvoie {'data': bytes, 'mime': 'image/png'|'image/jpeg'} ou None."""
    lines = text.splitlines()
    for i, line in enumerate(lines):
        m = _THUMB_START.search(line)
        if not m:
            continue
        kind = (m.group(1) or "").upper()
        mime = "image/png" if kind == "PNG" else "image/jpeg"
        # collecter jusqu'au marqueur de fin
        b64_parts = []
        for j in range(i + 1, len(lines)):
            if _THUMB_END.search(lines[j]):
                raw = "".join(b64_parts)
                try:
                    data = _b64.b64decode(raw)
                except Exception:
                    return None
                if len(data) < 20:
                    return None
                return {"data": data, "mime": mime}
            b64_parts.append(lines[j].strip())
        break
    return None


if __name__ == "__main__":
    # --- Tests ---
    samples = {
        "creality_klipper": """
; generated by Creality Slicer
; filament used [mm] = 1234.56
; filament used [g] = 4.32
""",
        "prusa": """
; Filament used: 2.34m
; estimated printing time (normal mode) = 1h 15m
""",
        "prusa_double": """
; Filament used: 2.34m / 3.2g
""",
        "cura": """
;Filament used: 5.6778m
;Layer count: 247
""",
        "raw_only": """
G1 X10 Y10 E0.5
G1 X20 Y10 E0.8
G1 X30 Y10 E0.95
""",
        "vide": "",
    }
    for name, txt in samples.items():
        r = parse_filament(txt)
        print(f"{name:15s} → {r}")

    # Vérifs
    assert parse_filament(samples["creality_klipper"])["g"] == 4.32
    assert abs(parse_filament(samples["creality_klipper"])["mm"] - 1234.56) < 0.01
    assert abs(parse_filament(samples["prusa"])["mm"] - 2340.0) < 0.01
    assert parse_filament(samples["prusa_double"])["g"] == 3.2
    assert abs(parse_filament(samples["raw_only"])["mm"] - 0.45) < 0.01
    print("\n✅ Tous les tests parsing passent")
    print("Conversion: 1234.56mm PLA →", mm_to_grams(1234.56), "g")