; generated by Creality Slicer 5.1
; filament used [mm] = 2147.9
; filament used [g] = 7.92
; estimated printing time (normal mode) = 42m 18s
M73 P0 R43
G21 ; mm
G90 ; absolute
G1 X10 Y10 E0.1
G1 X20 Y20 E0.3
M106 S255
G1 X30 Y30 E0.55
G28 X Y
M84